---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-initdb"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: "${APP}-initdb-secret"
    template:
      data:
        INIT_POSTGRES_DBNAME: ${APP}
        INIT_POSTGRES_HOST: ${CNPG_NAME:=pgsql-cluster}-rw.dbms.svc.cluster.local
        INIT_POSTGRES_USER: ${APP}
        INIT_POSTGRES_PASS: "{{ .${APP}_postgres_password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cnpg-users
    - extract:
        key: cnpg-operator
---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-pguser"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: "${APP}-pguser-secret"
    template:
      data:
        port: "5432"
        host: ${CNPG_NAME:=pgsql-cluster}-rw.dbms.svc.cluster.local
        ro_host: ${CNPG_NAME:=pgsql-cluster}-ro.dbms.svc.cluster.local
        user: ${APP}
        password: "{{ .${APP}_postgres_password }}"
        db: "${APP}"
        uri: postgresql://${APP}:{{ .${APP}_postgres_password }}@${CNPG_NAME:=pgsql-cluster}-rw.dbms.svc.cluster.local:5432/${APP}
        dsn: "host=${CNPG_NAME:=pgsql-cluster}-rw.dbms.svc.cluster.local port=5432 user=${APP} password={{ .${APP}_postgres_password }} dbname=${APP} sslmode=disable"
  dataFrom:
    - extract:
        key: /cnpg-users
