---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sparkyfitness-server
spec:
  interval: 30m
  path: ./kubernetes/apps/default/sparkyfitness/server
  components:
    - ../../../../components/volsync
    - ../../../../components/cnpg
  dependsOn:
    - name: cnpg-cluster
      namespace: dbms
    - name: longhorn
      namespace: longhorn-system
    - name: volsync
      namespace: volsync-system
    - name: akeyless-stores
      namespace: external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  postBuild:
    substitute:
      APP: sparkyfitness
      VOLSYNC_CAPACITY: 5Gi
      CNPG_NAME: pgsql-cluster
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sparkyfitness-frontend
spec:
  interval: 30m
  path: ./kubernetes/apps/default/sparkyfitness/app
  dependsOn:
    - name: sparkyfitness-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
