---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: decluttarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: decluttarr-secret
    template:
      data:
        config.yaml: |-
          general:
            test_run: false
          jobs:
            remove_failed_imports:
              message_patterns:
                - Not a Custom Format upgrade for existing*
                - Not an upgrade for existing*
          instances:
            radarr:
              - base_url: http://radarr.downloads.svc.cluster.local
                api_key: {{ .RADARR_API_KEY }}
            sonarr:
              - base_url: http://sonarr.downloads.svc.cluster.local
                api_key: {{ .SONARR_API_KEY }}
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: sonarr
