---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: seerr-secret
    template:
      data:
        API_KEY: "{{ .SEERR_API_KEY }}"
  dataFrom:
    - extract:
        key: seerr
