apiVersion: v1
kind: Secret
metadata:
    name: akeyless-secret
stringData:
    accessId: ENC[AES256_GCM,data:6mfIe8S4xLRLPB4jodv88g==,iv:gCwQo1yKgyOhDbMPpKpd/n+lXEDboM68kWrn2cmx9v4=,tag:WR0yePRfwRM7b39ilQLdKQ==,type:str]
    accessType: ENC[AES256_GCM,data:kxQCd3269yTIEg==,iv:/0T6TG/kfXsnDTfe/ZjIdSO4R5FFjPjKU8/cn8jtFvs=,tag:8xRz4YZRrHK0vkSZhFcoNw==,type:str]
    accessTypeParam: ENC[AES256_GCM,data:RglRAtigQjsg+HSrlvMoI/pO41ZNpJLZGGpT6C+WRn8lDbQHPbj59cH70jg=,iv:xq1aAmX3CwzQFSdSraGIIxPgTJDLTdG/7O1y0Zu7QkM=,tag:2mJRGK6LLtsnFT9/IptWRA==,type:str]
sops:
    age:
        - recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIKzFtajhSYVo4TFpRT1Qx
            a2xOZ2dnbTREMm9mOW05TE5OQU1BelU3YTFFCmFXZHJ1cmdzOE5SdFMvT0VkZjV2
            QjduRTdxMGx5NHZCVHBkN1lqZ0UvaFEKLS0tIDhKYmRDZXZyTXJDTFhlUzBJZ0xF
            aEJ0RWNNeHZmd2pRT2crWjUrZDU5b1kKG1HVam+sEyPom0FlnDAu0X2ZnqiwBScp
            7OBezgRWIXXH0QZqDMBN97IkRSqHRzIzCb4NuNQAITR7KawUfWKJFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T05:55:27Z"
    mac: ENC[AES256_GCM,data:dL2/zMUYgnTrgE9SPTOAFnOveC9WKMvVA0mNS+y/sjA70PoCoFAhyQKvaZCqmxbEYcCEYgLZxPNaVP1FjFwNwS0DMMEDQ/9vwtSdr6Jg3r8iZxebApzXQ5S3cWyLhO3fvHA5dMZBG/RiujoyrN5omiIIFbq35q8bqeexm53VeQA=,iv:j2g9q067ipBoLPn488jVnZ1jsMKBfWgMmE6lSowbKrA=,tag:r+SLnmc5ok41Y+f6BYNcXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
