apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vpn
spec:
  config: |-
    {
      "cniVersion": "1.1.0",
      "name": "vpn",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.50",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "0.0.0.0/0", "gw": "172.24.50.1" }
            ]
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
