---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tautulli
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: tautulli-secret
    template:
      data:
        TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
  dataFrom:
    - extract:
        key: tautulli
