apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Xr3P1nXTgoFlk8/srwLbmOYeQfx3MQlXf/hF3l5I+G+K3xSFoq3C8Q==,iv:5FyRx/ASYl+DqkdbEawcK+Q8co6euo0QkjyW4YmAHpQ=,tag:MIZUFEWX+RKcbCHLNoJuNw==,type:str]
sops:
  age:
    - recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eUw5WEFwZjVLWGZpYkZE
        WWsxeGZRQjAvSERxMDJxTmp3M3V3WDY5bVE4Ck85eGdFeE15UXZtL0FPRTVhQUd4
        S3l4NitHNUZBaUV1ZFRmcW5BYUxVbEUKLS0tIDdCOGZUWUV5U0N2ZXdRVitXc3NK
        MUJDWUEzbG5adjJVSlF6Tm0rZ3RISTgKU36M60oC0vgDInKLK8KgX8bghBjMUq0j
        ZZoAxHNesQru11t/AxJCOLbFBtkiZSK5PcpTwG0eOAgSWofIN3Bhtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:14:17Z"
  mac: ENC[AES256_GCM,data:QLzowmqtN8wzG+Bzadrvasxu8rik36S/jJ/FVlx6qkER1osV+k3k8p/6YOyumMvoiFOD8E2Utop+QvUQWl0Q8J/Q/OxGPcBhe3Ij3ViK0olGrV55aBZ+2f60HdkW9v6zZn3FyqgTS/fvDPS263WibGvnhS6Fp4Ji95plaNDkWjQ=,iv:uwmRLyw/MD39wWMID6Km7zjbXLZbxOgztpkDz2WsrA4=,tag:JVAiY+9vR6sX6UB/KRPa3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
