apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:L+gE7/rBgEGa0I04lKST/4q9kY72TxUvKARnABbZEVV9VO0kAt6Tuw==,iv:TXWjtanNH9WSdjqFlNsKeUQYwmyd8gGNyG4X7pOFFBg=,tag:hmZ3FfPtTKz+CakytmiWjA==,type:str]
sops:
  age:
    - recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUUVaYTNhb0NRM3JVWkVk
        dmE2L05jL2x1bzdLMDhaVnRPV0VoS0M2T2pnCjlTVjdCejNrZ0FESUxpSnhNZDFr
        SklvVWp3NGNlaXh3cHBaaEFWTU94TUUKLS0tICtvb24wQTNBdUZ4cDZYU256aW9O
        YjZmbmhUTkJqZ2tEMU4yeUpEWjFKZWcKLofyxU1Xckg5mIrYZ2GNUc4T4OW5GHsR
        2nbRrzdC5LPCs0+inF2f47UGm17CtzUrvMzKbjazJpNw3y9a/808vw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T04:54:03Z"
  mac: ENC[AES256_GCM,data:HxGNzR+EA6S1QWUy9qgymYaxmSzxKVBw8FN9bwt6vgwV/1RjbqWM7l2YVEeKHzWrK01HlujJq/p8yNU5OINgkHD8uIoQWbvV8DXryhckLTOLUTdF41lk+gbEPzZSxf+3DgVEUvMiDcYyuOzFZZ4IB6vYsNwI6BhyF0M8C4wmFak=,iv:UwOzetl5KKx3/HEa4gjPOeZ0VAG2v+BRGIQSBatasww=,tag:gMBhzNkA+bTaAgS5eUwHNQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
