---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: sparkyfitness-secret
    template:
      data:
        SPARKY_FITNESS_DB_HOST: ${CNPG_NAME:=pgsql-cluster}-rw.dbms.svc.cluster.local
        SPARKY_FITNESS_DB_PORT: 5432
        SPARKY_FITNESS_DB_NAME: "${APP}"
        SPARKY_FITNESS_DB_USER: "${APP}"
        SPARKY_FITNESS_DB_PASSWORD: "{{ .${APP}_postgres_password }}"
        SPARKY_FITNESS_API_ENCRYPTION_KEY: "{{ .SPARKY_FITNESS_API_ENCRYPTION_KEY }}"
        SPARKY_FITNESS_APP_DB_USER: "${APP}"
        SPARKY_FITNESS_APP_DB_PASSWORD: "{{ .${APP}_postgres_password }}"
  dataFrom:
    - extract:
        key: sparkyfitness
    - extract:
        key: cnpg-users
