apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:e+FZaBgUcUv7ozc=,iv:APHjDGALeMgs7QvKWhn18srtFRTkljglZNx962H+svY=,tag:y2HLDz0KnPzHKx+MkB4Eww==,type:str]
sops:
  age:
    - recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L2hKZzNlbC9WVzIwK1pn
        ZUNEV09Gdnk3elpkZEpSblpRemZNRGliOUdVCjFwcXFnN3o3NXp5VWE2dUNaT1FG
        VkxYTEdpd3dyMkxHTmtlN3BSdjh1VncKLS0tIHRFYW55Z2djYXNneU94aWtwckFn
        OGlhd2RJRThkTGdqeUE3ak9GaXh2MjAKRoIal7imYdJRqqxtAKEQ4jUQW+M41uwA
        P6+gCFKDpDpSaIeHHjZofJg0nnxXwDZLAtWu9n3HeMooFuuZa6pCGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T04:54:03Z"
  mac: ENC[AES256_GCM,data:74i9qAer2FW6yzWOFQv+raxqS+cEor6dqVIiCPLglaqxlPR22tFZqTD2PHXlrjfecaV8vsKkiKxM0scshlevMzdBR1NkiBY84GUCjUPHIiO5Rldqp3PouZY495AhMhHV9PfSWfVj0LacS5bC1RA9nCzcPo5yybNesNUpLzaLbqs=,iv:+FvAr4c5fbV77oMBRuwFzF1DVS7bgqcEHnCc0EH7wJU=,tag:NkZaONz1QF+aAEFRXngXdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
