apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:2/1lgytTCZWEWsU=,iv:TaS5R/xH6qPxPnA4re3ZXTB9L8RwS1LV622WNlNMEzw=,tag:WgyXPXIQooRScFQk51utDQ==,type:str]
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:lTX+FxD1FX9iiVU36qPmQVUP8Mgd8ZgtGoszLDPfwmw=,iv:x/CUGXCMxq+GMWC6p/29Y0hleUyfCKrOble6i1EKX7o=,tag:jmCicGGOFdyrIMzSqT6vag==,type:str]
sops:
    age:
        - recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bytOOUkzanRxSFkzekQr
            U0xybDhSQjlpMUNmeCtZVWdkQ1ZZZnBtYUJFCjRQWlFZek02SkFHaGxianVrY0N3
            ZE44ZWRrSU8vUkEzODVSZEp3RjM5YVkKLS0tIFFZaFhmM3U5MU4ycTQydGpnRkRK
            c0NBMU1hUTZ2OXQwQm91OTZQbzhKbWMKhHSuDNZKggla3l07hmSMO1l1cPCmLhxI
            Fis1NiYKELYBkQ0ihccEWlRMiq9G6mkGkJrdgFy420gXPHf0kHY0Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T20:19:22Z"
    mac: ENC[AES256_GCM,data:T5zuFRWgnrU4kGYO2hXd2Ceoc33p9NlLb/i/BgwHNQUCUh4vSv3B7BsM+lHzOx9f9EVxe4Zhb+DKuWuNBSNLeal1bQ8aZWsuFOTGJvELqAZ/8zoUpxKusJHp1LmVs9MD27N325Bi4DX0jy7KJZAfBuJBj8BNDPCHjTcsjbVgwmw=,iv:c14AMb6YeH92Vt/9bcpq/4hGmPBZTXpAHg61DlLacEA=,tag:8rEe1ufmbX+ZJ0sAdUrjxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
