apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:2/1lgytTCZWEWsU=,iv:TaS5R/xH6qPxPnA4re3ZXTB9L8RwS1LV622WNlNMEzw=,tag:WgyXPXIQooRScFQk51utDQ==,type:str]
sops:
  age:
    - recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bytOOUkzanRxSFkzekQr
        U0xybDhSQjlpMUNmeCtZVWdkQ1ZZZnBtYUJFCjRQWlFZek02SkFHaGxianVrY0N3
        ZE44ZWRrSU8vUkEzODVSZEp3RjM5YVkKLS0tIFFZaFhmM3U5MU4ycTQydGpnRkRK
        c0NBMU1hUTZ2OXQwQm91OTZQbzhKbWMKhHSuDNZKggla3l07hmSMO1l1cPCmLhxI
        Fis1NiYKELYBkQ0ihccEWlRMiq9G6mkGkJrdgFy420gXPHf0kHY0Xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:14:17Z"
  mac: ENC[AES256_GCM,data:/vAkvmLY2pSR2gStGv0ADWQORPfjnaLSQeF53lfUU1hSVhxOl5d64Y+q6SC6FXT4ms7vGqATez0lhgARycghWmwYjm8JeBFJ5Pu/RPUQuBvc1wkmG9UKZGStGLCXc19Y9N29kMAruDZsDEx9ryWocZGoVuTgRYgMdvPCqA1DjXk=,iv:V0P5EtDR0EMjYqu//9yxZZc/2Lban58Ebp2IYUZx+Co=,tag:HZtBeCrevv+BHhcxeARgwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
