apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:kSB4zk+RWQXnta+A+d4IGeIc9HEW4jNVVQgQS5ga8ig=,iv:PgK8Xg4tgc69Ka3i11mQ99g7jTJdIdK0+tj6T51uBb4=,tag:kA92AMZrrKi5w/vIqQNPzQ==,type:str]
sops:
  age:
    - recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZEVTU0h1VmswemNybDl1
        K09YdzJGcWxuZGg4cUI0MEdsdTh3WjFLckdzCkY4MTRkT2lPYStDUlViWUxVazV6
        c1hsZ0lRUTFuWFpPZ1JsY0cvaEk0KzgKLS0tIGpwenlRUzJpaDBjVXp4Yi9MK1pO
        LzJGMWlQRmhEOUhtOXZhSU1vRTVVck0KV7nNxqXoQd6FeAz75W4cjNF3AGBo5oiV
        mmfiZaeItDOeOLH+FQVGXmKv0Maj77J3aIy0jXhhYXunBAtzUbo9xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T04:54:03Z"
  mac: ENC[AES256_GCM,data:z/USUSMZTcGVVHu0XuvD42S+dxtY541ByIU59HB7YCF4uxLf11WQrxzAY4HVG6cU4T+leM6IzTac1CmUHdGfz6NpZ5741RK+vCTmM3r9kr5tw5k/AsSWyjt1XKxc2g4ZhUGQaeM80MJOhfaYzyyfDiPNoumfyqv6L+gEAodQ7xk=,iv:R40R4DURFnl4BZ0bAHmwR/JWl2TQWmJ1PwmcX45d2jc=,tag:gMJhaVQ/IYb2YeVk6IzFgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
