apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:kYUA1j2RWY0UphonxCVSyF5DGsylCj4LLufyy8vujSM=,iv:reHqUw+5w6NtS4+87zvlFjzqYjZvrNIrIf/5Uu4sJD0=,tag:py1WY5cn+wngddfQCSMYhQ==,type:str]
sops:
  age:
    - recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbjF3akVwYW9Qck5vY0pn
        cGtURlRpeVJMZG01UWRlVmxYajFiZGJMbEU4CmpBK1JTbm02SjJMY2w1Wk0rLzFO
        T1FNcTg5NWdocTVpUGRXZEkvZFh4UE0KLS0tIFFURkJnWUtJRjRBSGRaM2QvWjQ5
        SHRORUE1Y1lIQVFRUXN2THNLNnFXOW8KVgbm8DQ2CfmNNYEe5z7u5LDoXl9Des55
        QclKnr0/Tbw7FctMemPiAqxER1mWNYqoagK51eQT2QxYyf0A5CNtUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:14:17Z"
  mac: ENC[AES256_GCM,data:Ic45qHNq/G6DW+uQ1ufoCuXvlN0msG+4v01tMYuOdz9vZQcAm8I/2cieMR6wNjs/1LZ7KX79MGJgwSE/hoC1DZvfL96p4aUliMJazTPwASFpEjfEnOc4SpMoLKBOqnoGW4XyRu9aQC4mXvy46HhS8SLIM0g/vu9GsYWTWeygclA=,iv:Hy/vsBargiAZV59DH9y19iwcCIvMR1bfxpDShFqY1iI=,tag:gLsqxsnvPoVNE4h06llSBg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
