---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads

components:
  - ../../components/sops
  - ../../components/namespace

resources:
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
