---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster17.yaml
  - ./gatus.yaml
  - ./grafanadashboard.yaml
  - ./objectstore.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
  - ./service.yaml
