---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pgsql-cluster-barman
spec:
  cluster:
    name: pgsql-cluster
  schedule: "0 0 11 * * *" # Every day at 0300 PST / 0200 PDT
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  immediate: true
