---
apiVersion: v1
kind: Service
metadata:
  name: pgsql-cluster-loadbalancer
  annotations:
    lbipam.cilium.io/ips: 172.24.30.91
spec:
  ports:
    - protocol: TCP
      port: 5432
  selector:
    cnpg.io/cluster: pgsql-cluster
    cnpg.io/instanceRole: primary
  type: LoadBalancer
