---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops
  - ../../components/namespace

resources:
  - ./actual/ks.yaml
  - ./echo/ks.yaml
  - ./home-assistant/ks.yaml
  - ./lubelog/ks.yaml
  - ./matter-server/ks.yaml
  - ./scrypted/ks.yaml
  - ./teslamate/ks.yaml
  # - ./zigbee/ks.yaml
