apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:kf9sBn/Z01F90bB3OIBMv7HmplpdOStYt7d3KBY1x0imiuQOcD1m6Gyn9+DZhPcRUKaAEH4TMd+YzS8EeenjTyUvbAm/LSDTTTejb8RK/SbCqLZIhBZjCS6lJIZAhVeOab599T1807La/VK1NYbyxmxAFCAEKgcfjrKflc+3JoLUT4e5Xx1qV5XreGSo2aGyAkfSf2dXJNT3JHtM8vYzkJnOvml3T5rhWObfEbMTvRiCLJ+u,iv:0EOWBw3Zcy7TDQc95iJgAa08lsbgbqbGYfZClWC12L4=,tag:MlNdNGX8ZbECobaSGuWh/w==,type:str]
sops:
  age:
    - recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRVNqWkFKemF6MlVZNWhq
        TW9Kb2pram5NUEc4alp2R3ZTWUlvbWxUZ0JFCmw3VjRFYzdPZThRQitpb1drMFY1
        TS9rM0dSVU96UTgzMjVnZ2pqSE16UFkKLS0tIEk0RExESjBlOTBsczhkS0pZdWtZ
        K2dWd29MTjVBMW8rMkRBekxFdzRVTUkKAOuF2xz6KktntmNr0RaD6VM2Qz5qGkNB
        /fYBxQ+TPJfyoA4Mxym5BOtenp0jVFjIAF84vtJXKt+CgJCCFcWw5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:14:17Z"
  mac: ENC[AES256_GCM,data:giuk8x8T+W7+V4v5nTn7UCcfL6Hh5628BQPv3VEw2NUGuRLn7XZp7lWXxTT4AIpgsYTSR3d0q84F4gBitI9yWRSu/e9EDw2p4YSssFIC9RHuPYIFbDG/MaX/7O9NN6HcS+ouJZpNb14L6Wa71rrkn2uDogVGi4qdbzwfsqMQvMw=,iv:TLcBjnLwUkyG+304TK3lT+/+obl6P0pRxt4Cd3CQIJQ=,tag:8WNTcz0K1tBaIHYl+TBDoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
