apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:trdLD7Wdz0S0naYIveWrwRWIpCthhTI/7I0JQvgcSL15sj6sOsnrr0MfKJzmfDBu34pRNBQ7XwpCNf56sRMNFc6gONDAojMSfJ1nLyTp6JskYdNfoElRhn9wwKdXBFkeF3x88Yhuc1u92/GD5DNM5wuMScN7tmi+OzVuKYHe901jWuCp2Ls3cxOF1qyfaOldMaVziopfvbf/c9+KcrZTDjZQIycvPwNz6PyV8IUtshzMI9Vj,iv:SWgg4m1TSyJVElofCQ8lQ1nD8+w3V3ekL9zcnoV8lnI=,tag:yvG65bc3IBVmIHOaElT16Q==,type:str]
sops:
  age:
    - recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVHFkaDcvQnRya1hpcHZG
        UEtFbXREZGhhWVdRZGRuN2VlWXVuNmpnK2hJCndyNEc5M2JkS1c4SEJQQWhHQnJ0
        d1JLS29LUFV2amhjbTZEeGFGTFVSa1kKLS0tIEQvOXBGZ1pPR1FBYlJmZTBBT2Fa
        UHF2SEEvSWxVeG4zMVkvWU51R0J1dFkK4kKtsBAfOs85PxnjP0NTB5vwRO1ns1mv
        iIMqFK9ALzopaMo6GOrYJTm+4TV4vOzzTaGHiuaY2mEiHPeVWTdNjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T04:54:04Z"
  mac: ENC[AES256_GCM,data:anvYoBeeVo14nuaNN/9BKujJyfU4A3GqHDiKlfY72C8oQwdGc4l/ftmRlPNP0vtteUuCEEhzMh4BBWDGTtxAVcLUcgFxfKjNb/1sfpm1Q2zyljMt5PUM0QbNe+xl9idPmRogoxHEihPy1kUEWfcaOjH07agdeu64+voHg5ckQbE=,iv:g6H8TSlsCKd9RSsDGgt3hEH1Vjet7NjAxbTGPjOaQmQ=,tag:GnF+tjQpjCnp3r8v3GytNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
