apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2kkSAEswOQD5NWUYDgXAwh0MICeusf2p8lynl/Esc+vksP2SayFErQ==,iv:xxqQhiwKZfYpnH/rrDvqWlw4qlYggz7gFaHCmlEeN6I=,tag:cG2MaX3OUcyAszUL0cgwVg==,type:str]
sops:
  age:
    - recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIKzFtajhSYVo4TFpRT1Qx
        a2xOZ2dnbTREMm9mOW05TE5OQU1BelU3YTFFCmFXZHJ1cmdzOE5SdFMvT0VkZjV2
        QjduRTdxMGx5NHZCVHBkN1lqZ0UvaFEKLS0tIDhKYmRDZXZyTXJDTFhlUzBJZ0xF
        aEJ0RWNNeHZmd2pRT2crWjUrZDU5b1kKG1HVam+sEyPom0FlnDAu0X2ZnqiwBScp
        7OBezgRWIXXH0QZqDMBN97IkRSqHRzIzCb4NuNQAITR7KawUfWKJFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:14:17Z"
  mac: ENC[AES256_GCM,data:DzcACmCtJHaksT/JMWNZHdST1Va7YAIzE5CbFuIqvqPfBk9yHHGn5rQzAYdkDQMjCgg+XfShW/pb+8b3rPthw9JT869oNHHI4PXJW0oDpnE8DwOXiJ07FqgWdVS+zoh9XIMT/iJ71DNv6LY3w171drBccHqvbuEyfD4dKa7gZfc=,iv:bnJPvtjv7izvvLTrMC/X+xlNLNiD3YnrlcLZy/pUUI4=,tag:FfpURxEWjiFwgTqAFHfEUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
