---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia-sync-r2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: kopia-sync-r2-secret
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        KOPIA_REPOSITORY: filesystem:///repository
        S3_BUCKET: volsync-kopia-sync
        S3_ENDPOINT: "{{ .CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-local-template
    - extract:
        key: cloudflare

