---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lubelog
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: lubelog-secret
    template:
      data:
        # Database Init
        INIT_POSTGRES_HOST: "postgres17-rw.dbms.svc.cluster.local"
        INIT_POSTGRES_DBNAME: &db lubelog
        INIT_POSTGRES_USER: &user "{{ .LUBELOG_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &pass "{{ .LUBELOG_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        POSTGRES_USER: *user
        POSTGRES_PASSWORD: *pass
        POSTGRES_DB: *db
        # Smtp
        MailConfig__EmailServer: "{{ .SMTP_HOST }}"
        MailConfig__EmailFrom: Lubelog <noreply@${SECRET_DOMAIN}>
        MailConfig__Port: "587"
        MailConfig__Username: "{{ .SMTP_USERNAME }}"
        MailConfig__Password: "{{ .SMTP_PASSWORD }}"

        #TODO: FIX OIDC ERROR

        # #Oidc
        # OpenIDConfig__Name: Authelia
        # OpenIDConfig__ClientId: Lubelog
        # OpenIDConfig__ClientSecret: "{{ .OIDC_LUBELOG_CLIENT_SECRET }}"
        # OpenIDConfig__AuthURL: https://auth.${SECRET_DOMAIN}/api/oidc/authorization
        # OpenIDConfig__TokenURL: https://auth.${SECRET_DOMAIN}/api/oidc/token
        # OpenIDConfig__RedirectURL: https://lubelog.${SECRET_DOMAIN}/Login/RemoteAuth
        # OpenIDConfig__LogOutURL: https://auth.${SECRET_DOMAIN}/logout
        # OpenIDConfig__Scope: openid email profile
        # OpenIDConfig__UsePKCE: "true"
        # OpenIDConfig__DisableRegularLogin: "true"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: generic
