---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lubelog
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: lubelog-secret
    template:
      data:
        # App
        POSTGRES_USER: "${APP}"
        POSTGRES_PASSWORD: "{{ .${APP}_postgres_password }}"
        POSTGRES_DB: "${APP}"
        # Smtp
        MailConfig__EmailServer: "{{ .SMTP_HOST }}"
        MailConfig__EmailFrom: "{{ .SMTP_FROM }}"
        MailConfig__Port: "{{ .SMTP_PORT }}"
        MailConfig__Username: "{{ .SMTP_USERNAME }}"
        MailConfig__Password: "{{ .SMTP_PASSWORD }}"
  dataFrom:
    - extract:
        key: cnpg-users
    - extract:
        key: smtp
