---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: kopia-secret
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-local-template
