---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sparkyfitness-frontend
spec:
  chartRef:
    kind: OCIRepository
    name: sparkyfitness
  interval: 30m
  values:
    controllers:
      sparkyfitness-frontend:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          sparkyfitness-frontend:
            image:
              repository: ghcr.io/codewithcj/sparkyfitness-frontend
              tag: v0.16.4.7@sha256:a89c8c2ab451e591ac238b78f5715a95679d083b06ed7713e30043d7fb144de7
            env:
              SPARKY_FITNESS_LOG_LEVEL: debug
              SPARKY_FITNESS_SERVER_HOST: sparkyfitness-server.default
              SPARKY_FITNESS_SERVER_PORT: 3010
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 64M
    service:
      app:
        controller: sparkyfitness-frontend
        ports:
          http:
            port: 80

    route:
      app:
        hostnames:
          - fitness.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
